### ISSUE TITLE
Option to Disable Merlin (important for Windows)

### ISSUE THREAD

**Issue by superherointj** [reasonml-editor/vscode-reasonml#102]
Merlin windows support is broken.

Having an option to disable Merlin is desirable for:
* Suppressing errors.
* Enabling BsRefmt. (doesn't work if Merlin is broken.)
* Enjoying syntax highlighting error free.

Even if Merlin is sorted out it still makes sense having a way to disable it. Because:
* The 'ocaml-for-windows' hack shouldn't be required.
* Merlin is optional.
* Merlin might be replaced by another tool later. (Like bsb errors)
* For debug purposes
* Merlin might become broken again. Who knows?
* Other uses we are not aware now.

Either Merlin works or it's necessary to allow disabling for scenarios it doesn't work.

**Comment by yawaramin** [comment]
This relates to https://github.com/facebook/reason/issues/1190

**Comment by OlegLustenko** [comment]
you can try https://github.com/reasonml/reasonml.github.io/issues/109

it mostly works for me out of the box, only 1 requirements you need to set this in vscode settings
```json
 "reason.path.ocamlfind": "ocamlfind.cmd",
  // The path to the `ocamlmerlin` binary.
  // "reason.path.ocamlmerlin": "ocamlmerlin.cmd",
  // The path to the `opam` binary.
  "reason.path.opam": "opam.cmd",
  // The path to the `rebuild` binary.
  "reason.path.rebuild": "rebuild.cmd",
  // The path to the `refmt` binary.
  "reason.path.refmt": "refmt.cmd",
  // The path to the `refmterr` binary.
  "reason.path.refmterr": "refmterr.cmd",
  // The path to the `rtop` binary.
  "reason.path.rtop": "rtop.cmd",
```

**Comment by superherointj** [comment]
Did: npm install -g ocaml-on-windows
Now I have ocaml 4.04.0 in path + tools in Windows Command Prompt (good!)

Refmt is working on VSCode. And on saving code reformatted as expected. (great!)
But Merlin is still not working...

Current VSCode configuration:
`
{
    "reason.path.ocamlfind": "ocamlfind.cmd",
    "reason.path.ocamlmerlin": "ocamlmerlin.cmd",
    "reason.path.opam": "opam.cmd",
    "reason.path.rebuild": "rebuild.cmd",
    "reason.path.refmt": "refmt.cmd",
    "reason.path.refmterr": "refmterr.cmd",
    "reason.path.rtop": "rtop.cmd",
    "reason.formatOnSave": true
}
`
Current VSCode errors:
`
ocamlmerlin error: sh: 1:
ocamlmerlin error: C:UsersUsernameAppDataRoaming: not found
ocamlmerlin error: sh: 1: C:UsersUsernameAppDataRoaming: not found
ocamlmerlin error: sh: 2: pm: not found
`
I find really weird this 'C:UsersUsernameAppDataRoaming' error.

**Comment by fhelwanger** [comment]
It seems that merlin isn't finding your project's path.

Did you opened a *file* or a *folder*? If you opened a file, try opening your project's root folder.

**Comment by superherointj** [comment]
I have opened the project folder exactly where '.merlin' file is.
That is the project's root folder already.

**Comment by fhelwanger** [comment]
Oh, it's happening for me too. I get:

```
ocamlmerlin error: sh: 1: C:Tempocaml
eason-react-example: not found
```

Something must have changed lately that is using `\` as an escape char 😞

**Comment by frankwallis** [comment]
Also related https://github.com/ocaml/merlin/pull/684

**Comment by superherointj** [comment]
It is working now. I'll close this.

**Comment by frankwallis** [comment]
@superherointj good news! What changed to make this work? do I need to upgrade merlin?

**Comment by superherointj** [comment]
Just updated VSCode extension to version 1.0.1. There was a patch this night. I already had 'ocaml-on-windows' installed.

**Comment by superherointj** [comment]
It seems the problem persists if Merlin file is present.
