### ISSUE TITLE
Refmt/bsrefmt not working on Windows

### ISSUE THREAD

**Issue by superherointj** [reasonml-editor/vscode-reasonml#103]
On Windows Command Prompt "refmt" doesn't exist/work. But "bsrefmt" does (is available and works). 
To solve this tried to configure extension to switch from "refmt" to "bsrefmt" but it didn't work. 
Configuration follows:
{
"reason.path.refmt": "bsrefmt"
}
Also tried variations like:
"C:\Users\user\AppData\Roaming\npm\node_modules\bs-platform\bin\refmt.exe"
("C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\bs-platform\\bin\\refmt.exe") [with two Backslash] Still didn't work.

On Cygwin & ocaml-env-win, both refmt and bsrefmt work flawlessly with VSCode extension. Tested with command:
C:\Ocaml64\usr\local\bin\ocaml-env-win.exe -- "C:\\Program Files\\Microsoft VS Code\\Code.exe" %1

So problem is restricted to Windows standard environment.

**Comment by chenglou** [comment]
cc @kyldvs who had the same problem afaik

**Comment by kyldvs** [comment]
Yeah I cannot get this extension to recognize `refmt` command either. All the commands work fine in VSCode integrated terminal, so I'm unsure why this extension would be unable to run the commands.

**Comment by superherointj** [comment]
Found a way to get 'refmt' to work on Windows w/ VSCode. But it is a hack.
`
npm install -g ocaml-on-windows
`
Now ocaml will be installed and on path + tools in Windows Command Prompt.
Then, configure VSCode extension options this way:
{
"reason.path.ocamlfind": "ocamlfind.cmd",
"reason.path.ocamlmerlin": "ocamlmerlin.cmd",
"reason.path.opam": "opam.cmd",
"reason.path.rebuild": "rebuild.cmd",
"reason.path.refmt": "refmt.cmd",
"reason.path.refmterr": "refmterr.cmd",
"reason.path.rtop": "rtop.cmd",
"reason.formatOnSave": true
}
And Refmt will work on VSCode.
But Merlin is still not working... [and lots of errors are shown while that isn't fixed]

I don't think this is a proper solution and this issue should be kept open as a reminder.

**Comment by freebroccolo** [comment]
Okay I'll try to reproduce this on windows. I thought there was a recent fix that was supposed to get `.cmd` working though.

**Comment by superherointj** [comment]
'bsrefmt' only worked after installing the 'ocaml-on-windows' hack. 
So, tested removing 'ocaml-on-windows' npm bin links and isolated what is interfering with 'bsrefmt'.
Conclusion: Having or not having 'ocamlmerlin' is what interferes with 'bsrefmt' functioning.
Also confirmed that  '.cmd' is not required. 'bsrefmt' works fine when 'ocamlmerlin' is available, and it doesn't when it is not.

**Comment by freebroccolo** [comment]
Okay. If I'm understanding the situation correctly that makes a little more sense. If `ocamlmerlin` is not found, the server does not initialize properly to begin with and so nothing else in the extension is really expected to work in that case. I'm not sure if it's worth trying to change that or not. It should probably be clarified somehow either way though.

**Comment by superherointj** [comment]
Having something working is better than nothing.
Without Merlin, we could still have:
* Syntax Highlighting
* Refmt 
* No errors from Merlin, all supressed.
Posted this issue:
[](https://github.com/reasonml-editor/vscode-reasonml/issues/102)
And another person confirmed problems too... have a look on it.

**Comment by superherointj** [comment]
It is now working.
