### ISSUE TITLE
CodeLens not working for me

### ISSUE THREAD

**Issue by kaaloo** [reasonml-editor/vscode-reasonml#105]
Hi,

I'm working through [Marcel Cutts slides](https://marcelcutts.github.io/reason-react-talk/#/) and I noticed that the automatic display of type signatures isn't working in my vscode installation.  What could I double 
check to debug this ?

![tickets re woop-react-boston visual studio code_065](https://user-images.githubusercontent.com/67010/30809652-bcbccc4a-a202-11e7-80a6-567efd618ded.jpg)

-- frustrated

**Comment by freebroccolo** [comment]
If the codelens is not showing up it's likely due to some problem communicating with merlin. How do you have your development environment configured and how did you install the Reason tooling? Is the `ocamlmerlin` binary in your path when you try to run it from a shell?

**Comment by kaaloo** [comment]
Thank you for your help !

I installed merlin using opam and it is indeed available:

`luis@juno:~$ which ocamlmerlin
/home/luis/.opam/4.05.0/bin/ocamlmerlin
`

I installed the reason tooling globally using yarn as follows:

`yarn global add bs-plateform`

In fact before I installed merlin there was an error in vscode about not being able to communicate with merlin but that is gone now and I see `[merlin]` in the status bar.

I am on Ubuntu 17.04 btw.

**Comment by freebroccolo** [comment]
I'm not sure what could be causing this if you indeed have `ocamlmerlin` in your path and Code is no longer complaining about it being missing. Is there a repository somewhere for the project you are trying to use it with? I will try to reproduce on a Linux environment.

**Comment by paulosuzart** [comment]
Hi. Same thing here. Ubuntu 16.10. In the vscode tray I can see the `[merlin]` and if you hover the mouse you see `merlin server online`. No way to make it work with `.re`, but I don't know how it works with `.ml` files.

**Comment by paulosuzart** [comment]
For some reason `ocamlmerlin` was pointing to 4.05.0 instead of 4.02.3 even after doing the `eval 'opam config env'`. Solution as as simple as removing merlin from 4.05.0 and switch bat to 4.02.3.
