### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by freebroccolo** [reasonml-editor/vscode-reasonml#106]
The current README was written back when I wasn't really expecting anyone to use this. It should probably be rewritten from scratch at this point.

Stuff to include:

- [ ] fix broken links
- [ ] updated "getting started" section
- [ ] animations of important features (codelens, completion, diagnostics, hover, outline, …)
- [ ] "contributing" section (code structure and server, how to get started, link to easy issues)
- [ ] mention OCaml support
- [ ] move more detailed discussion (e.g., case splitting) to the wiki

**Comment by jchavarri** [comment]
A couple of things that weren't immediately obvious to me and might be useful on the "contributing" section:

- Linking `ocaml-language-server` repo code with `npm link` inside the `vscode-reasonml` folder
- How you can debug both projects simultaneously if you open them in two separate vscode windows and attach the `ocaml-lang-server` debugger to the existing process.
- How vscode will overwrite the extension if it's installed (i used to uninstall and install it all the time 😅 )

**Comment by pbiggar** [comment]
Very small related issue: the README says "Search for reasonml and install Reason <version> by Darin Morrison.". Searching for "reasonml" doesn't find anything at this point in time. It does when searching for "reason".
