### ISSUE TITLE
Support side panel outline view

### ISSUE THREAD

**Issue by freebroccolo** [reasonml-editor/vscode-reasonml#109]
This can be done using the [views](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) part of the API. This will be implemented in the server but supported through custom messages since there is no official part of the LSP for this functionality yet.

Some care should be taken regarding efficiency. We already request outlines from merlin in order to compute the codelens. Ideally we should reuse the results from that request for the tree view as well. This will complicate the implementation since it will probably have to involve some sort of caching.

**Comment by freebroccolo** [comment]
I started to implement this but it turns out someone already made a generic outline view extension [here](https://github.com/patrys/vscode-code-outline). I guess that it must be populating the view with the information already provided for the outline command palette functionality. Clients for other languages could do something similar. Anyway it seems to work well enough that we can just depend on that until something official is added to the language server protocol so I will close this for now.

**Comment by Enzojz** [comment]
Yes, also I found this feature in Inoide-F#, it's quite useful.

**Comment by freebroccolo** [comment]
Can you please explain what you expecting to see that you don't see? I'm not sure I understand what you are asking for. Below is a screenshot of how it looks on one of my example projects. The information provided to the outline view comes directly from Merlin.

![shot-opt](https://user-images.githubusercontent.com/151197/31833565-2d9ae1ac-b588-11e7-9a17-eba7de0a03ad.png)
