### ISSUE TITLE
support querying opam through palette

### ISSUE THREAD

**Issue by freebroccolo** [reasonml-editor/vscode-reasonml#11]

**Comment by Khady** [comment]
As reason isn't really using opam, do we really want this feature? I tend to think that a separated plugin for opam would be a better solution if someone really want to manipulate opam from vscode. Also if we need to support both opam 1 and 2 it will be a nightmare.

**Comment by freebroccolo** [comment]
Hmm, maybe it would be better to have this in a separate extension. To be honest, I sort of view this plugin as being (at least usable) for both Reason and OCaml so as far as I'm concerned it's okay to support tools for either languages. But as far as implementation is goes, I would probably only focus on opam 2 at this point.

**Comment by freebroccolo** [comment]
I think I'm going to close this for now since I'm not sure it's a good idea anymore.
