### ISSUE TITLE
Does not work in VSCode 1.17

### ISSUE THREAD

**Issue by silentdragonz** [reasonml-editor/vscode-reasonml#111]
Extension can't be enabled in 1.17. It seems to be locked to 1.16.1. 

`Extension is not compatible with Code 1.17.0. Extension requires: 1.16.1.`

**Comment by chenglou** [comment]
I wonder if it's just a matter of bumping the version? @jchavarri are you on 1.16.1 as well?

**Comment by jchavarri** [comment]
My version also updated and saw the same problem, but uninstalling and reinstalling the extension fixed it :man_shrugging:

The `engine` value [is `1.16.1`](https://github.com/reasonml-editor/vscode-reasonml/blob/master/package.json#L17), the problem should go away if we change it to `^1.16.1`. I created [a branch](https://github.com/reasonml-editor/vscode-reasonml/compare/master...jchavarri:update-engine-inclusive) to fix it but then realized it would require publishing a new version. cc @freebroccolo

**Comment by freebroccolo** [comment]
Should be fixed now. Thanks for letting me know.
