### ISSUE TITLE
"rename symbol" can not change cross files!

### ISSUE THREAD

**Issue by yyc-git** [reasonml-editor/vscode-reasonml#115]
vscode version: v1.17.1
reason plugin version: v1.0.2
OS Version: mac OS X 10.10.5

now "rename symbol" can change related changes in the current file, can't change other related files!

Could anyone fix it?

**Comment by freebroccolo** [comment]
This extension ultimately relies on [merlin](https://github.com/ocaml/merlin) to gather the information it needs for renaming. Unfortunately, merlin does not currently (to my knowledge) have the necessary functionality built in to make this kind of global renaming easy to support. There is an upstream issue that you might want to keep an eye on though (or comment on) at https://github.com/ocaml/merlin/issues/610.

I do have some ideas on how global renaming could be supported by us despite the lack of support in merlin but I don't know yet whether such a workaround would be efficient enough for a released feature. At the moment I have no ETA on when this might land in a release.

**Comment by yyc-git** [comment]
Thanks for your reply and your effort to support it~

I wish we can make it work in future, Thanks a lot.

**Comment by Khady** [comment]
I think that one good inspiration on how to do the remaining over a whole project is ocp-grep. As it is able to find a symbol over a whole codebase.

**Comment by jchavarri** [comment]
@freebroccolo Could we take advantage of `bsb` for this? cc @bobzhang

**Comment by freebroccolo** [comment]
@jchavarri I was wondering about that. It might be possible. I don't know enough about `bsb`'s capabilities to say for sure.

**Comment by bobzhang** [comment]
Bsb definitely has a global view of the project and its dependencies but we need some collaboration with Merlin to make use of cmt files cc @let-def

**Comment by yyc-git** [comment]
and it's great that if we can "rename file name/module name" across files!

now if I rename the file name, the related files which open the module don't rename the related module name!
e.g.
there are two files:
fileA.re
fileB.re

fileB.re open FileA module

if rename fileA to fileC, fileB.re should change to open FileC module!!!

**Comment by jchavarri** [comment]
@freebroccolo Does the extension rename across files now? I looked into the history but couldn't find the relevant code, was this fixed upstream in Merlin?

**Comment by jchavarri** [comment]
I can create an issue upstream in bsb if needed :) From what was written above that seems like the least complex solution.

**Comment by freebroccolo** [comment]
@jchavarri the main reason I closed this and some other issues is just to try and keep the number of active issues manageable. Some of these issues (this one in particular) won't be resolved for the foreseeable future unless changes happen to upstream projects (or until the native rewrite happens and we have lower level access than the current merlin API provides).

An upstream issue for bsb might be a good idea if you think there's a realistic chance to see it implemented though.
