### ISSUE TITLE
"find all references" can not cross files!

### ISSUE THREAD

**Issue by yyc-git** [reasonml-editor/vscode-reasonml#116]
vscode version: v1.17.1
reason plugin version: v1.0.2
OS Version: mac OS X 10.10.5

now "find all references" can only find reference in current file, can't find references in other files which reference to it!

Could anyone fix it?

**Comment by freebroccolo** [comment]
The answer to this one is basically the same as https://github.com/reasonml-editor/vscode-reasonml/issues/115.
