### ISSUE TITLE
"Failed to establish protocol: v3" with new reason-scripts app

### ISSUE THREAD

**Issue by girvo** [reasonml-editor/vscode-reasonml#127]
I created a brand-new ReactReason app using `reason-scripts`, and opened the folder with VSC, but was greeted by the above error:

```
Request initialize failed with message: onInitialize: failed to establish protocol v3
```

If I was to take a wild guess, it'd be because we don't support the new v3 syntax yet? A `.merlin` file exists, and aside from the more "IDE"-like features its working somewhat, but I wanted to check if perhaps I'd done something incorrectly!

Cheers,
Josh

**Comment by freebroccolo** [comment]
The `v3` here has to do with the version of the protocol it uses to communicate with merlin. I think the only way this should happen is if you somehow have a very old version of `ocamlmerlin` in your PATH. How do you have your development environment set up?

**Comment by girvo** [comment]
@freebroccolo Ah, that'd do it! I setup my OCaml environment up yonks ago; I'll give `opam upgrade` a try and see what happens :) Cheers!

**Comment by freebroccolo** [comment]
I'll go ahead and close this. Let me know if there's still a problem.
