### ISSUE TITLE
“Go to Definition” from inside *.ml library file doesn't work

### ISSUE THREAD

**Issue by hendysg** [reasonml-editor/vscode-reasonml#136]
From a SomeFile.re I can right click -> "Go to Definition" on a standard library function that I use (in this case `Format.printf(...)`) and it will jump to the definition as I expect (in this case `./node_modules/bs-platform/lib/ocaml/format.ml`)

But inside format.ml, "Go to Definition" doesn't work for me. In this case, in format.ml, `printf` calls `fprintf`. When I try to "Go to Definition on fprintf, it says "No definition found for fprintf"

Not sure if this a bug / missing feature? Or I simply miss some settings?

TIA

**Comment by freebroccolo** [comment]
I think this is probably something to do with how the ocaml stdlib is packaged by `bs-platform`. If you install ocaml through `opam`, the second jump-to-definition called within `format.ml` does succeed, and you can keep following back until `make_printf` in `camlinternalFormat.ml`.

Can you open an issue about this in the bucklescript repo?

**Comment by freebroccolo** [comment]
cc @bobzhang @chenglou

**Comment by bobzhang** [comment]
I will try to see if I can reproduce it

**Comment by hendysg** [comment]
@freebroccolo I'm happy to open an issue in bucklescript repo too. But since I don't fully understand the (possible) bug, I'd just be copy pasting mostly the same description. 

Also I see that @bobzhang is also active in bucklescript repon (maintainer?) and he's going to try reproducing.

Do you think I should still open an issue in bucklescript? I'm affraid I'll just be creating noise.

**Comment by chenglou** [comment]
Can repro. Not sure why. Afaik jump-to-definition requires putting the correct .merlin file at the root of bucklescript's folder (right now bs ships with a wrong one that contains @bobzhang's local paths), but that didn't work either
