### ISSUE TITLE
Saving .ml file deletes its content

### ISSUE THREAD

**Issue by Spriithy** [reasonml-editor/vscode-reasonml#139]
I installed the extension this morning and was quite astonished that saving any `.ml` file simply deleted the file's content.

![peek 2017-11-13 09-45](https://user-images.githubusercontent.com/2387743/32716736-6a3a9882-c857-11e7-89f7-95d4be485d67.gif)

Any insights ?

**Comment by freebroccolo** [comment]
Do you have `formatOnSave` enabled in your settings? If so, do you have `ocp-indent` installed?

**Comment by Spriithy** [comment]
`opam install ocp-indent` made it :) Thank you. I thought the plugin would use its own shipped version of the tool.

**Comment by freebroccolo** [comment]
No problem. I plan to make this better behaved soon when tools are missing.
