### ISSUE TITLE
ocamlmerlin: command not found

### ISSUE THREAD

**Issue by jiyinyiyong** [reasonml-editor/vscode-reasonml#141]
Installed `Reason` extension in VS code. Cloned `reason-react` repo. Loaded a file, got the message `ocamlmerlin: command not found`.

Anything else I need to install? I checked that I have `ocaml` installed with `brew` in my macbook.

**Comment by freebroccolo** [comment]
How did you install the reason tooling? Through `opam` or `reason-cli`? If you are using opam, you will need to have merlin and reason installed too (`opam install merlin reason`). Also, please try updating to the latest plugin release `1.0.14`.

**Comment by jiyinyiyong** [comment]
None of them. I guessed from the error messages that I should install something... but didn't know which of them. Thanks for replying. Will try.
