### ISSUE TITLE
bsb generates non-working .merlin when file name matches project name

### ISSUE THREAD

**Issue by Lokeh** [reasonml-editor/vscode-reasonml#146]
repro steps:
1. Create new project using bsb and open in VS Code:
```
 ~/Code/reason > bsb -init test -theme basic-reason
Making directory test
Symlink bs-platform in /Users/r627543/Code/reason/test
 ~/Code/reason > code test
```

2. Create new file called `test.re` in the `src` directory

3. Write any code, e.g.:
`let hello = () => Js.log("hello");`

4. Build
5. Note that it shows errors about module `Js`
6. Reload window / restart editor
7. Code lens no longer works

Additional info:
```
~/Code/reason > which ocamlmerlin refmt ocamlmerlin-reason
/Users/r627543/.nvm/versions/node/v8.6.0/bin/ocamlmerlin
/Users/r627543/.nvm/versions/node/v8.6.0/bin/refmt
/Users/r627543/.nvm/versions/node/v8.6.0/bin/ocamlmerlin-reason
```

**Comment by freebroccolo** [comment]
@chenglou @jchavarri @bobzhang any idea what could be causing this? It sounds like some bsb/merlin interaction issue. As far as I can tell, there's nothing in the language server that should care about project names like this.

**Comment by jchavarri** [comment]
I could repro, thanks @Lokeh for the detailed steps!

@freebroccolo Both `codeLensResolve` and `completionResolve` handlers are not being called in this particular file, and `hover` gets called, but tracking the response from merlin I see `Error: Unbound module Test`.

I then went and removed the line `FLG -open Test` from `.merlin` and the issue gets fixed.

**Comment by freebroccolo** [comment]
> I then went and removed the line FLG -open Test from .merlin and the issue gets fixed.

cc @bobzhang

**Comment by freebroccolo** [comment]
Closing this since I've created an issue for it upstream.
