### ISSUE TITLE
Strings marked by {| and |} are not highlighted correctly

### ISSUE THREAD

**Issue by yminsky** [reasonml-editor/vscode-reasonml#150]
In particular, they're highlighted as if they were code, rather than strings. Here's an example.

![image](https://user-images.githubusercontent.com/715302/34341608-03a3c322-e969-11e7-86d4-c3bdc97f905b.png)

**Comment by freebroccolo** [comment]
Thanks. This will be fixed in the next release.

**Comment by freebroccolo** [comment]
Should be fixed in the new version just published (`1.0.17`). Let me know if not.

**Comment by yminsky** [comment]
Looks like it works too me. Thanks!
