### ISSUE TITLE
Record field punning confuses syntax highlighter

### ISSUE THREAD

**Issue by yminsky** [reasonml-editor/vscode-reasonml#155]
Consider the following two screenshots. The first is an ordinary example of syntax highlighting:

![image](https://user-images.githubusercontent.com/715302/34633038-647f7ace-f247-11e7-8922-5765b11857b9.png)

In the second, I've changed an explicit use of record fields with a use of record punning

![image](https://user-images.githubusercontent.com/715302/34633037-647d521c-f247-11e7-9121-b498ce8f3468.png)

In this second case, the syntax highlighting has gotten completely confused.

**Comment by freebroccolo** [comment]
Should be fixed in the newly published `1.0.20`.

**Comment by yminsky** [comment]
Fixed. Thank you!
