### ISSUE TITLE
Weird characters appended to file on every save

### ISSUE THREAD

**Issue by venil7** [reasonml-editor/vscode-reasonml#156]
a file with the following content:

```
type hello = {
  name: string,
  is: bool
};
```

gets `l;` appended to it every time I save

**Comment by freebroccolo** [comment]
Has this happened on any other file? Does it still happen if you completely close the editor and then open the file again?

**Comment by ncthbrt** [comment]
Can confirm that this is an issue. Closing and then reopening the file in vscode stops the behavior.

**Comment by creativecoder** [comment]
I have also seen this issue. `c;` was being appended to one of my `.re` files until I closed and reopened that file.

**Comment by freebroccolo** [comment]
I think this should be fixed in version `1.0.23`.
