### ISSUE TITLE
Warn: Cannot find merlin binary at "ocamlmerlin".

### ISSUE THREAD

**Issue by dangodev** [reasonml-editor/vscode-reasonml#158]
Completed the [installation instructions](https://reasonml.github.io/docs/en/global-installation.html#recommended-through-npm-yarn), and after that and installing the VS Code extension, I get the following warning:

```
[Warn] Cannot find merlin binary at "ocamlmerlin".
```

Are the additional steps needed to install merlin due to setup changes?

**Comment by freebroccolo** [comment]
Can you describe your development environment? How is it set up and which platform are you on? Are you using `nvm`?

**Comment by dangodev** [comment]
macOS, nodenv, Node 9.4.0, NPM 5.6.0, VS Code 1.20.0-insider.

Actually, after troubleshooting, it was an issue with the [install scripts](https://github.com/reasonml/reason-cli/issues/62#issuecomment-354364414). After getting that sorted out, the editor plugin works just fine.

**Comment by freebroccolo** [comment]
Okay, I will close this then. Thanks.
