### ISSUE TITLE
fix symbol rename for annotated function arguments

### ISSUE THREAD

**Issue by freebroccolo** [reasonml-editor/vscode-reasonml#16]

**Comment by Khady** [comment]
I tag as bug but I'm not sure to know what the problem is.

**Comment by freebroccolo** [comment]
I vaguely remember the rename function not working properly for something like `bar` given `let foo bar baz = …`. I'll have to do some testing again because I think there were some other issues too but I don't remember what exactly.

**Comment by freebroccolo** [comment]
This is an issue that will need to be fixed upstream. Closing for now.
