### ISSUE TITLE
syntax highlighting(parsing) error on string containing "(*)"

### ISSUE THREAD

**Issue by arbipher** [reasonml-editor/vscode-reasonml#165]
```
let x = "foobar (*)";;
let y = "foobar (*)";;
```
syntax highlighting is error for the second line. I guess "(*)" in the first line is recognized as an (ill-formed) comments.

**Comment by freebroccolo** [comment]
I'm not able to reproduce. This is what it looks like for me:

<img width="384" alt="screen shot 2018-02-06 at 20 23 33" src="https://user-images.githubusercontent.com/151197/35896910-d2a5185e-0b7b-11e8-8f38-05215c9dc98c.png">

Can you post a screenshot of what you are seeing? What version of the extension are you using?

**Comment by arbipher** [comment]
I cannot reproduce it either...sorry for that. I guess I may mismatch some other comment parentheses.
