### ISSUE TITLE
Sorry, but there is no formatter for 'reason'-files installed

### ISSUE THREAD

**Issue by patoncrispy** [reasonml-editor/vscode-reasonml#166]
I'm trying to develop an app with create-react-app and `reason-scripts` and it works fine, but for some reason, I'm unable to format my Reason React code. I have `editor.formatOnSave` set to `true`. If I try 'Format Selection' using `Ctrl+K Ctrl+F` with code highlighted, I get the message in the title.

Is there some specific configuration I need to get the formatting to work? 

Is there any more information I need to provide to clarify the problem?

**UPDATE**
I'm using WSL. I installed Reason using the instructions [here](https://github.com/reasonml/reasonml.github.io/issues/195#issuecomment-335008528). I completely removed my instance of WSL and installed a fresh copy and that didn't change anything.

---
OS:  Windows 10
VS Code Version: 1.19.3
Plugin Version: 1.0.21

**Comment by tkreis** [comment]
I had the same problem but on Mac. After running those steps I got it to work: https://github.com/reasonml-editor/vscode-reasonml/issues/117#issuecomment-340549703

**Comment by patoncrispy** [comment]
@tkreis I just updated my issue mentioning I'm using WSL. I also totally reinstalled everything and there are still issues. :(

**Comment by freebroccolo** [comment]
Unfortunately this extension isn't officially supported on WSL just yet and I do not have much experience configuring Reason tooling in that setting. I would kindly suggest posting a question to one of the linked threads in the meantime since you're more likely to get a helpful response. You might try asking on the discord `#editorsupport` channel too.

**Comment by patoncrispy** [comment]
Thanks, @freebroccolo. I posted a question on Discord #editorsupport but no response yet. :( Is there a way to get this support without WSL?

**Comment by freebroccolo** [comment]
Native Windows support (without WSL) using `bsb-native` is also planned but as with WSL support it is not yet available in release. If those instructions you linked to are not working I think the only other real alternative would be to use a VM for the moment. Maybe @superherointj can help get your configuration working though.

**Comment by freebroccolo** [comment]
It looks like the OP might have managed to things working with another configuration.

**Comment by patoncrispy** [comment]
Yeah, @freebroccolo while I didn't have much luck with WSL I decided to partition a bit of my hard drive and create an Ubuntu boot. All working wonderfully. :)
