### ISSUE TITLE
No definition found for 'JS'

### ISSUE THREAD

**Issue by svsool** [reasonml-editor/vscode-reasonml#167]
Hi, thank you for this extension and your work and time!

How to reproduce this bug:

Run in terminal
```
bsb -init test -theme basic-reason
echo 'Js.log("okay");' >> ./test/src/test.re
open ./test/ -a /Applications/Visual\ Studio\ Code.app/
```

Open project in VSCode, go to `src/test.re` and check definition of `Js`, you will see `No definition found for 'JS'`

Maybe this is a known limitation that you cannot give the same name to the file in ./src folder as project name. For instance if I rename test.re to TEST.re or test1.re (not Test.re) then resolving of definitions will work. Sorry if it's a trivial thing, I'm new to ReasonML.

**Comment by svsool** [comment]
Probably related https://github.com/reasonml-editor/vscode-reasonml/issues/58 but didn't find the answer there to my problem

**Comment by freebroccolo** [comment]
> Maybe this is a known limitation that you cannot give the same name to the file in ./src folder as project name. For instance if I rename test.re to TEST.re or test1.re (not Test.re) then resolving of definitions will work. Sorry if it's a trivial thing, I'm new to ReasonML.

Thanks for the report.

It's not a trivial thing but I think this is a known problem when using Bucklescript. I have created an upstream issue about it [here](https://github.com/BuckleScript/bucklescript/issues/2477).

**Comment by freebroccolo** [comment]
@jordwalke @chenglou Would it be possible to add a warning about this somewhere in the Reason docs for setting up a project with Bucklescript?
