### ISSUE TITLE
Bug when preference > parameters > editor.formatOnSave=true

### ISSUE THREAD

**Issue by oteku** [reasonml-editor/vscode-reasonml#168]
Bug reproduce on VSCode 1.19.3 with vscode-reasonml 1.0.21, on Ubuntu and OSX.

Pre-requisite : having vscode-reasonml activate and user parameter `"editor.formatOnSave": true,
` 

Step to reproduce : 
* create a .re file
* write some code in vscode
* save the file (cmd+s)
* erase the content  in vscode
* save the file (cmd+s)
=> vscode paste the previous content (and repeat it each time you do a cmd+s)

vscode-reasonml  desactivate / `"editor.formatOnSave": true,` => OK
vscode-reasonml  activate / `"editor.formatOnSave": false,` => OK
vscode-reasonml  activate / `"editor.formatOnSave": true,` => KO

**Comment by freebroccolo** [comment]
This should be fixed in version `1.0.23`.
