### ISSUE TITLE
merlin occurrences doesn't understand bucklescript string interpolation

### ISSUE THREAD

**Issue by rauschma** [reasonml-editor/vscode-reasonml#181]
Renaming a variable that is mentioned inside an interpolation literal `{j|...|j}` removes the substitution syntax around the variable name. For example:

Before:

```
let foo = 123;
{j| Foo 1: $(foo)|j};
{j| Foo 2: $(foo)|j};
```

After:

```
let bar = 123;
{j| Foo 1: bar|j};
{j| Foo 2: bar|j};
```

**Comment by freebroccolo** [comment]
Are you doing this string interpolation in a Bucklescript project? As far as I'm aware, Reason doesn't support string interpolation directly (and neither does OCaml).

The renaming functionality in this extension works via merlin so I'm guessing there is something about the way the string interpolation is implemented that merlin doesn't understand.

I could perhaps do some sort of postprocessing to try and detect when this happens but that's a hack I'd rather avoid. This is an issue that should be fixed upstream if possible.

@chenglou @bobzhang @jordwalke @let-def any thoughts on how to deal with this?

**Comment by let-def** [comment]
As far as merlin is concerned, the solution would be to not include the `$(` `)` in the expression location.
However this is clearly not a case that I had in mind when implementing this feature :).

**Comment by freebroccolo** [comment]
I've created an issue for this upstream [here](https://github.com/BuckleScript/bucklescript/issues/2582).
