### ISSUE TITLE
Support |. as an infix op

### ISSUE THREAD

**Issue by yawaramin** [reasonml-editor/vscode-reasonml#185]
`|.` is going to be the new 't-first' infix syntactic operator, see https://github.com/BuckleScript/bucklescript/issues/2342

E.g.

```ocaml
let result = Belt.Set.Int.(empty |. add 5 |. has 5)
```

**Comment by freebroccolo** [comment]
I believe this should already be highlighted as an operator since the highlighting for operators works according to the lexical specification in the OCaml language reference.

**Comment by yawaramin** [comment]
Ah, perfect. Gotta love backwards-compatible changes!
