### ISSUE TITLE
Wierd Editor Error

### ISSUE THREAD

**Issue by idkjs** [reasonml-editor/vscode-reasonml#187]
* this repo is a straight copy of https://github.com/apollographql/reason-apollo/tree/master/examples/swapi

If you run `yarn start` and `yarn webpack` the file runs.

As soon as you open a file, example, `src/Feed.re`, webpack and bsb recompile and dont produce the bs.js files causing webpack to throw an error saying it cant find the files.

* initial run:

[![https://gyazo.com/8f171bc8df53e761b1659a6e4c30847b](https://i.gyazo.com/8f171bc8df53e761b1659a6e4c30847b.gif)](https://gyazo.com/8f171bc8df53e761b1659a6e4c30847b)

* then open Index.re:

<a href="https://gyazo.com/cfef088cdffddba2a1c4a6e8fa65b56b"><img src="https://i.gyazo.com/cfef088cdffddba2a1c4a6e8fa65b56b.gif" alt="https://gyazo.com/cfef088cdffddba2a1c4a6e8fa65b56b" width="724"/></a>

* Strangely, doesnt happen every time. Originally happened with Feed.re but then I could not reproduce.

https://github.com/idkjs/swapi-example#wierd-editor-error

**Comment by jchavarri** [comment]
@idkjs Do you happen to have `bsb` included in `reason.diagnostics.tools`?

**Comment by idkjs** [comment]
i do. It stopped when i turned off format on save.
<img width="452" alt="screen shot 2018-03-15 at 5 45 16 pm" src="https://user-images.githubusercontent.com/2370391/37477739-bb68e8d6-2878-11e8-8153-0cd850294dc4.png">

**Comment by freebroccolo** [comment]
Interesting. It may be the case that merlin is crashing because the file is being modified by the formatter while merlin is trying to parse and analyze it.

@idkjs have you modified the `reason.debounce.linter` setting? Can you try setting it to a higher value (maybe +500 or +1000) and see if that makes the problem go away?

**Comment by idkjs** [comment]
@jchavarri so how would you build the project? And does that mean that watch is happening automatically with bsb in diagnostic tools?

**Comment by idkjs** [comment]
With debounce at 1000, formatOnSave:true, you start with this:

<a href="https://gyazo.com/6f56a4ea131269e29cfdf12921178484"><img src="https://i.gyazo.com/6f56a4ea131269e29cfdf12921178484.png" alt="https://gyazo.com/6f56a4ea131269e29cfdf12921178484" width="845"/></a>

and end up with this when you add a word, here Star becomes Star Wars. 
Note the comma being added by refmt(?):

<a href="https://gyazo.com/7f2bf0ccc251a13838d7506c0f48496b"><img src="https://i.gyazo.com/7f2bf0ccc251a13838d7506c0f48496b.png" alt="https://gyazo.com/7f2bf0ccc251a13838d7506c0f48496b" width="753"/></a>

So maybe debounce setting is not the issue.

**Comment by freebroccolo** [comment]
Thanks for the details. If the formatting is not finishing in a clean fashion but instead failing, that could cause the problem with merlin. I'm not seeing why `refmt` should be failing though.

@idkjs would you mind opening a brief issue about this in the reason repo and linking here so that the reason devs will see it?

cc @jordwalke @chenglou @bobzhang thoughts on this? Could there be a problem with how the trailing comma before the final `}` is handled for some reason?

**Comment by chenglou** [comment]
@idkjs thanks for the report! You're on an old version of bs-platform. You need to upgrade to 2.2.2

**Comment by idkjs** [comment]
So that solved the problem. Are you guys automatically updating bs-platform some way when there is an update?

**Comment by chenglou** [comment]
You mean this plugin? It doesn’t take care of that. You’d upgrade it yourself through yarn/npm for your project

**Comment by jchavarri** [comment]
>  so how would you build the project? And does that mean that watch is happening automatically with bsb in diagnostic tools?

@idkjs If `bsb` is on `reason.diagnostics.tools`, the project is built automatically every time you save a file. There is no watch needed, as each save operation triggers `bsb`.

I am interested to know if the problem with merlin goes away if you stop running `yarn start` from the command line. In theory you wouldn't need `debounce`.

**Comment by idkjs** [comment]
@chenglou ok. so just watch for updates. Thanks.

**Comment by idkjs** [comment]
@jchavarri so that would be  `yarn build` then `yarn webpack`?

**Comment by jchavarri** [comment]
No, just `yarn webpack`. `yarn build` runs `bsb` too,  so it's not needed.

**Comment by idkjs** [comment]
Well, its all stopped since update bs-platform to 2.2.2. You are correct about bsb running without yarn start. If i refresh after making edits with just weback -w its updating the project.
