### ISSUE TITLE
Code Lens doesn't work

### ISSUE THREAD

**Issue by Neptunao** [reasonml-editor/vscode-reasonml#190]
Hey. I use the latest VSCode with ReasonML externsion and after 2 last releases of vscode it suddenly stopped to show code lense.

I enabled code lens explicitly in config:
```    
    "reason.diagnostics.tools": [
        "merlin",
        "bsb"
    ],
    "reason.codelens.enabled": true,
    "reason.codelens.unicode": true,
```

Could you please help me? 

- Extension Name: reasonml
- Extension Version: 1.0.30
- OS Version: Linux x64 4.10.0-38-generic
- VSCode version: 1.21.1
- ReasonML version: 3.1.0
- bsb version: 2.2.3
- merlin version: The Merlin toolkit version next, for Ocaml 4.02.3

**Comment by freebroccolo** [comment]
I don't know what would have changed in the last couple versions that would cause this.

How do you have the Reason tooling installed? If you are using something like nvm, this will often cause the server to not work properly.

Can you verify that things still aren't working even on a clean project?

Can you check if you are affected by [this](https://github.com/BuckleScript/bucklescript/issues/2385) issue?

Can you provide an example project that shows this behavior?

**Comment by Neptunao** [comment]
Now I see that this issue affects only nested functions. Is it by design?
![image](https://user-images.githubusercontent.com/1561458/37841184-21bc0a5c-2ed0-11e8-9e10-80360643d51f.png)

**Comment by freebroccolo** [comment]
Thanks for clarifying.

Yes, the codelens only displays types for the functions that are listed in the code outline response from the OCaml tooling used in the backend. That allows us to avoid having to reparse the document manually. We may try to support local functions at some point in the future but it will require redesigning significant parts of the backend so it probably won't happen any time too soon.
