### ISSUE TITLE
Codelens not working

### ISSUE THREAD

**Issue by knyzorg** [reasonml-editor/vscode-reasonml#191]
I cannot appear to get codelens working in VSCode. I did nothing more than following instructions from the official documentation and yet.. nothing.

Interestingly though, it works fine for .ml files.
![image](https://user-images.githubusercontent.com/10255546/37867696-8235b5d4-2f72-11e8-90ab-52fcc360693e.png)

**Comment by knyzorg** [comment]
It would appear I followed instructions too blindly. The opam installation broke the npm installation. Removing all opam packages makes everything JustWerk(tm)

**Comment by voodoos** [comment]
I encountered that issue as well but wanted to keep my opam install as I use OCaml for other purposes than Reason.

Fortunately you can make both installs coexist by specifing the correct path to `ocamlmerlin` in the `vscode-reasonml` options : 
```
"reason.path.ocamlmerlin": "/usr/local/bin/ocamlmerlin"
```

(you can use the `which -a ocamlmerlin` command to find the correct path for your install)
