### ISSUE TITLE
vscode-reasonml job launch trying to connect to https://github.com/reasonml-editor/vscode-reasonml/

### ISSUE THREAD

**Issue by shishini** [reasonml-editor/vscode-reasonml#193]
I cant repeat this, but
This is roughly what happened 

- I installed the vscode-reasonml plugin  
- open an ml file
- I pressed alt-enter a couple of times thinking it can compile/run the file  or the selection in an ocaml interactive shell

But instead, I see in kubuntu task bar, a notification about a job trying to connect to this link https://github.com/reasonml-editor/vscode-reasonml/

i left the job running for a while, nothing happened so i closed it 

i tried to repeat the behaviour with no success

any clue what could have happened, why was the plugin trying to connect to this link

**Comment by freebroccolo** [comment]
That link is the extension repository. I'm guessing that when you installed the extension and activated it (and it pulled up the extension description), the editor probably pinged the repository. There's nothing in the extension logic itself that directly calls out to this repository though.

**Comment by freebroccolo** [comment]
This was almost certainly due to the fact that the screenshot for the extension description (the `README.md`) is pulled from this repository.
