### ISSUE TITLE
Enable Emmet support

### ISSUE THREAD

**Issue by MarcCoquand** [reasonml-editor/vscode-reasonml#196]
Hello,

there is no documented way of enabling Emmet support for .re files. It would be very nice to have.

**Comment by tigp** [comment]
hey @MarcCoquand I think you could just add this to the settings
```
"emmet.includeLanguages": {
    "reason": "javascriptreact"
}
```

**Comment by freebroccolo** [comment]
I'm going to close this since it looks like the issue was resolved. If someone wants to make a PR to add a note about it in the README that would be welcome.
