### ISSUE TITLE
Underscore / lowdash error

### ISSUE THREAD

**Issue by feluxe** [reasonml-editor/vscode-reasonml#197]
Hi there!

In this code snippet the `_` in the map function is marked as an Error:

```reason
module Decode = {
    let dogs = json : array(dog) =>
        Json.Decode.(
            json
            |> field("message", array(string))
            |> Array.map(_, dog => dog)
        );
};
```

This is the error message:

> [refmt] 868 UNKNOWN SYNTAX ERROR

Despite getting this error in the Editor, it compiles without problem.

I'm using the latest release of *reasonml-editor/vscode-reasonml*.

**Comment by jchavarri** [comment]
@feluxe if you run `refmt --version` from the command line, what's the output?

**Comment by feluxe** [comment]
Reason 3.0.4 @ 731e605

**Comment by jchavarri** [comment]
`731e605` is not the latest version, it should show `Reason 3.0.0 @ bee43b0` (disregard the 3.0.0, that's a bug on the `--version` flag, the relevant thing is the commit hash).

**Comment by jchavarri** [comment]
Closing for now as it seems a versioning problem. Feel free to reopen if the issue persists.
