### ISSUE TITLE
Extension does not always show up in vscode search

### ISSUE THREAD

**Issue by michallepicki** [reasonml-editor/vscode-reasonml#199]
This extension does not show up when looking up `reasonml` in the vscode extensions search. It does show up when looking for `reason` though.

Ideally it would pop up when looking for:
- ocaml (currently works, 2nd entry)
- reason (currently works, 1st entry)
- reasonml (currently doesn't work)
- bucklescript (currently doesn't work)
- vscode-reasonml (currently doesn't work)

It may be possible to fix it through modifying extension description and/or name, but I'm not exactly sure how VSCode search works.

**Comment by freebroccolo** [comment]
Thanks for the report. Unfortunately there are only a limited number of keywords we can use for the package description. I'll try changing a few of them and seeing if it helps though.
