### ISSUE TITLE
syntax highlighter confused by type definition using more than one `and`

### ISSUE THREAD

**Issue by kevinbarabash** [reasonml-editor/vscode-reasonml#205]
This came up as I was working on a mutual recursive type definition involve three different types.  The screenshot includes a more minimal reproduction of the issue.

<img width="412" alt="screen shot 2018-05-04 at 12 18 36 am" src="https://user-images.githubusercontent.com/1044413/39612836-b611872e-4f30-11e8-9adb-2a248acf4aaf.png">

**Comment by freebroccolo** [comment]
Thanks for the report. I think this is a dupe of #57.
