### ISSUE TITLE
bsb can be referenced from node_modules

### ISSUE THREAD

**Issue by f0rr0** [reasonml-editor/vscode-reasonml#208]
I use:

```
"reason.diagnostics.tools": [
  "merlin",
  "./node_modules/bs-platform/lib/bsb"
]
```

to use the local `bs-platform` for diagnostics (so that the error messages are actually based off of the version of `bs-platform` referenced in my `package.json`, the global version might be out of sync from the local one). However, https://github.com/reasonml-editor/vscode-reasonml/blob/d2cc25dd17125ff51435b45917c48e3b74ebb84f/package.json#L73 complains that the value can't be anything other than `bs` or `merlin`

This does not prevent me from using it though.

**Comment by jchavarri** [comment]
Thanks for the report.

Adding a path to `diagnostics.tools` doesn't work, the binary used is still the globally available one. 

If you want to point to a custom path, you can use a different option: `reason.path.bsb`. We're currently about to merge a PR that will change the default value of that setting to point to the local `node_modules` version (https://github.com/freebroccolo/ocaml-language-server/pull/120).

Closing this for now as there's no actions to be taken, but feel free to reopen if you think there's still an issue.
