### ISSUE TITLE
After latest  update, ocp-indent integration no longer works

### ISSUE THREAD

**Issue by jonsterling** [reasonml-editor/vscode-reasonml#216]
After the latest update, when I try to ask ocp-indent to format my file (which I have configured to do on save), I receive the following error in the output console:

```
[Error - 9:36:30 PM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Bad argument
  Code: -32603 
```

Any idea what's going on?

**Comment by freebroccolo** [comment]
Should be fixed now.
