### ISSUE TITLE
[merlin] A syntax error occurred.

### ISSUE THREAD

**Issue by mudrz** [reasonml-editor/vscode-reasonml#217]
I get the following not-so-useful syntax errors:

```
[merlin] A syntax error occurred. Help to improve this message: https://github.com/facebook/reason/blob/master/src/README.md#add-a-menhir-error-message
```

Shouldn't this extension show the "improved message" ? Is there a setting I might have missed?

**Comment by freebroccolo** [comment]
Thanks for the report. The generation of error messages about syntax are usually the responsibility of the command line tooling (parser/compiler).

Would you be willing to create an issue for this in the [reason](https://github.com/facebook/reason) repository (along with a snippet of the code that is causing it)?

**Comment by mudrz** [comment]
I will create, but just to clarify - this is what I am doing - for example putting an extra `;` at the end of `</div>;`

```fsharp
let make = (_children) => {
  ...component,
  render: _self => <div> 5 </div>;
};
```

<img width="1116" alt="screen shot 2018-05-28 at 7 37 11" src="https://user-images.githubusercontent.com/9587050/40597420-0e4e7c22-624a-11e8-972e-3177215fd113.png">

> The generation of error messages about syntax are usually the responsibility of the command line tooling

Does this mean that the underlying reason for the syntax error can only be shown in the terminal?

**Comment by freebroccolo** [comment]
> Does this mean that the underlying reason for the syntax error can only be shown in the terminal?

It's not that the error messages can only be shown in the terminal but rather that the actual parser and the rest of the reason language tooling is not part of this extension. It's maintained as a separate project. What it's saying if you follow that link is that you can submit a patch to the reason repository to improve the error messages that the parser produces. If someone were to do that, the editor would show that improved message automatically.

**Comment by mudrz** [comment]
Thanks, I opened a new issue in reason
