### ISSUE TITLE
Cannot find merlin binary at "ocamlmerlin".

### ISSUE THREAD

**Issue by bifunctor** [reasonml-editor/vscode-reasonml#229]
Hi all
When I start VSC I've a warning:

> Cannot find merlin binary at "ocamlmerlin".  

I am using UBUNTU 18.04 and with following node global packages installed:

```
/home/developer/.nvm/versions/node/v10.1.0/lib
├── bs-platform@3.1.5
├── npm@6.1.0
└── reason-cli@3.2.0-linux
```
Do I have to do additional setup?  
Thanks

**Comment by mlms13** [comment]
I also got that warning on Ubuntu 18.04 with NVM when I was first getting the system set up a couple days ago, but for me the global install of `reason-cli@3.2.0-linux` (which I see you've also done) took care of it.

What output do you get for `which ocamlmerlin`?

For me, it's `/home/michael/.nvm/versions/node/v10.4.1/bin/ocamlmerlin`

**Comment by bifunctor** [comment]
First of all, thanks for your answer.  
I've got:
```
developer@monad:~$ which ocamlmerlin
/home/developer/.nvm/versions/node/v10.5.0/bin/ocamlmerlin
```  
What am I doing wrong?

Thanks

**Comment by freebroccolo** [comment]
This has come up before and NVM is known to cause problems when trying to use the reason command line tooling through the editor. The issue has to do with the fact that it does not properly initialize the shell environment but the language server expects to be launched in a shell environment so that it can also work with opam. I do not recommend using NVM with reason.

@chenglou @jordwalke would it be possible to add a warning about nvm to the set up instructions page for installing reason tools?

**Comment by mlms13** [comment]
> [NVM] does not properly initialize the shell environment

Is there a related NVM issue for this, or more discussion on the specifics somewhere? I'm mostly curious because I've been using Reason and vscode-reasonml with a working language server and basically no issues ever since I ran `npm install -g reason-cli@3.2.0-linux`.

**Comment by freebroccolo** [comment]
@mlms13 I don't know if there is a single issue but from a quick search these look related https://github.com/creationix/nvm/issues/1533 https://github.com/creationix/nvm/issues/1290 https://github.com/creationix/nvm/issues/739. I remember searching before and having seen issues like this going back for quite awhile.

This is a complicated problem and it's not entirely the fault of nvm but also due to the very unreliable nature of shell environment initialization across the different platforms and shells. It's extremely difficult to get consistent, working behavior everywhere.

**Comment by mlms13** [comment]
Ah thanks. I see there are definitely a lot of complicated variables at play here. I'm using `zsh`, which may have something to do with why I'm lucky and NVM+Reason tooling seems to work for me? :confused:

**Comment by bifunctor** [comment]
How should I solve the problem? Can I just ignore it?

**Comment by freebroccolo** [comment]
Did you try without NVM? If it works and you don't need NVM, then I'd just do it that way.

**Comment by bifunctor** [comment]
OK, I will try. Thanks

**Comment by chenglou** [comment]
Added a note. Thanks.

**Comment by johnhaley81** [comment]
Note for people who do use (or need to use) nvm and a workaround for how to get it to work:

- Make sure you have a default node version set in nvm and that your tooling is installed in that version's global package folder
- I have a script in my `~/.zshrc` that loads up nvm to my default node version when ever I type in a command for a node binary or other specific apps.

```bash
declare -a NODE_GLOBALS=(`find ~/.nvm/versions/node -maxdepth 3 -type l -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)

NODE_GLOBALS+=("node")
NODE_GLOBALS+=("nvm")
NODE_GLOBALS+=("npm")
NODE_GLOBALS+=("yarn")
NODE_GLOBALS+=("atom")
NODE_GLOBALS+=("atom-beta")
NODE_GLOBALS+=("code")

load_nvm () {
    export NVM_DIR=~/.nvm
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
}

for cmd in "${NODE_GLOBALS[@]}"; do
    eval "${cmd}(){ unset -f ${NODE_GLOBALS}; load_nvm; ${cmd} \$@ }"
done
```

This script will initialize the nvm environment when trying to run anything it finds in the `NODE_GLOBALS` envvar. 

- When starting atom/vscode/whatever make sure to at least start it from the CLI. If you start it from there then you'll be good after that. If you just start it from somewhere else then it won't be initialized properly and you're going to run into this issue. After it's running you can open projects, double-click links, etc that open in the respective app and things will be fine, it's just that initial load that's the main problem.

I have to use nvm and this is the best workaround I have for getting everything to play nice. I still run into the occasional `Cannot find merlin binary at "ocamlmerlin".` and that means that the app wasn't launched properly. Relaunching from the CLI will solve that problem with the above in place.

**Comment by mateusfccp** [comment]
I'm getting this error, but I'm not using NVM, I insatalled ocamlmerlin through OPAM.

**Comment by SaswatPadhi** [comment]
Same here. I installed `ocamlmerlin` via opam and recently started seeing this error.

**Comment by runvnc** [comment]
I think You can put this in your settings.json for Visual Studio Code (assuming this is the same extension I am using):

``` json
    "ocaml.merlinPath": "/home/runvnc/.opam/4.10.0/bin//ocamlmerlin",
    "reason.path.ocamlmerlin": "home/runvnc/.opam/4.10.0/bin/ocamlmerlin"
```
You need to change it to the actual ocamlmerlin path (`which ocamlmerlin`).
