### ISSUE TITLE
Is the Code Outline extension extension still necessary?

### ISSUE THREAD

**Issue by gomespereira** [reasonml-editor/vscode-reasonml#232]
Outline view is now available by default in VS Code, and better, it's in the Exporer Tab.

Is the Code Outline extension still necessary? It is installed by the OCaml and Reason IDE extension and in the current version it's not possible to uninstall it.

I know this is not a big deal but I wanted at least to report it.

**Comment by junchih** [comment]
Hey @freebroccolo , I think this issue has already became an emergency bug now.

As [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) said, 

> This extension is now unpublished from Marketplace. You can choose to uninstall it.

I'm new to ReasonML & VSCode, I do everything as the [README](https://github.com/reasonml-editor/vscode-reasonml#getting-started) said. And when I open VSCode, the Developer Tools got some error logs says,

> Extension 'freebroccolo.reasonml' failed to activate. Reason: unknown dependency 'patrys.vscode-code-outline'.

**Comment by junchih** [comment]
Very fast, thx guys. My VSCode seems being fixed.
