### ISSUE TITLE
Simplify simplest workflows

### ISSUE THREAD

**Issue by yurug** [reasonml-editor/vscode-reasonml#242]
I am looking for an IDE compatible with OCaml that I could suggest to beginners, especially Microsoft Windows users. Many people pointed me to this vscode plugin and I see that it enjoys a lot of nice features. 

However, I cannot convince myself that a beginner (understand: someone that has *never* written code before) would not be lost in this IDE because it seems that it is not simple to do simple things. Typically, I assume that a beginner wants to:
1. Open a single file named `foo.ml`.
2. Write code inside the buffer until there is no more typing error.
3. Execute the resulting module.

Do I miss some features or plugins that would make this workflow possible _without using the terminal_? I see that step 1 can be performed thanks to the menu (File -> New) and that step 2 is simply "editing" but I do not see how step 3 can be done easily (again, without typing any command on the terminal).

(As I am not a vscode user, there are significant odds that this issue is not justified. My apologies if this is the case.)

**Comment by freebroccolo** [comment]
Unfortunately for OCaml there is no fully automatic workflow, at least as far as I understand what you are seeking here.

The tooling that is needed for the IDE to work must be installed through OPAM or something similar, all of which require using a command line interface. Likewise, setting up a project to build properly requires some use of command line tools as well, especially if the developer wants to use external libraries or develop in the REPL.

I don't think this is so much an issue about how the IDE is setup so much as it is just the reality of developing OCaml projects currently. In that regard, OCaml might not be an ideal language to use given the criteria you have in mind. (I'm not sure what would be a better substitute either though).
