### ISSUE TITLE
execvp(ocamlmerlin-server) (no such file) error since upgrading to reason 3.3.3/bs-platform 4.0.5

### ISSUE THREAD

**Issue by tmepple** [reasonml-editor/vscode-reasonml#243]
MacOS v10.13.6

Everything has been working great for months until I upgraded bs-platform to v4.0.5 (both globally and in-project) and reason-cli (globally) to 3.3.3-macos.  

Now when I try to open any `.re` file the extension throws an error:

```
ocamlmerlin error: execvp(ocamlmerlin-server): No such file or directory merlin path: /Users/tepple/.asdf/installs/nodejs/10.8.0/.npm/lib/node_modules/reason-cli/bin/ocamlmerlin-server socket path: /var/folders/gs/klj2134gn/T//<not computed yet>
```

I looked in that referenced directory and the `ocamlmerlin` executable does exist... just like it did before.  If I run `./ocamlmerlin` directly in that directory I get the same error message:

```
tepple@tme-imac-2014: bin (master)$ ./ocamlmerlin
execvp(ocamlmerlin-server): No such file or directory
merlin path: /Users/tepple/.asdf/installs/nodejs/10.8.0/.npm/lib/node_modules/reason-cli/bin/ocamlmerlin-server
socket path: /var/folders/gs/6v085qc96nn_hd5tmq3nzgc80000gn/T//<not computed yet>
``` 

This might actually be an issue with https://github.com/reasonml/reason-cli since I have an older version in another directory which when I run `./ocamlmerlin` it works.

<img width="440" alt="screen shot 2018-08-15 at 4 12 37 pm" src="https://user-images.githubusercontent.com/1711033/44170677-0db85680-a0a6-11e8-99ce-fa969d8d9f9c.png">

**Comment by tmepple** [comment]
Thanks @freebroccolo for the help... maybe it has something to do with my use of `asdf` for nodejs version management but it's weird since before upgrading `reason-cli` and `bs-platform` it worked great for months.  So I could keep working I've been testing jaredly's RLS (which is working) and it seems like this is an isolated problem for me so I will close.

**Comment by pascalw** [comment]
For what it's worth I'm running into this as well, also after upgrading `reason-cli`. It looks like the latest version of `reason-cli` simply doesn't include `ocamlmerlin-server` anymore:

```
❯ ls /Users/Pascal/.asdf/installs/nodejs/8.9.1/.npm/lib/node_modules/reason-cli/bin
_storePath         ocamlmerlin-reason refmt              rtop
ocamlmerlin        reactjs_jsx_ppx_v2 refmttype          utop
```

**Comment by pascalw** [comment]
Ok looks like the binary was always called `ocamlmerlin`, but that binary seems to be broken in the latest `reason-cli` (`3.3.3-macos`). The binary from the previous version (`3.3.2-macos-betabeta`) is working. I'll open an issue with `reason-cli`.

**Comment by pascalw** [comment]
Issue was confirmed in `reason-cli` and a fix was merged the master already 🚀 https://github.com/reasonml/reason-cli/issues/87
