### ISSUE TITLE
Plugin stopped working - ocamlmerlin error: Fatal error: exception Unix.Unix_error

### ISSUE THREAD

**Issue by mralj** [reasonml-editor/vscode-reasonml#244]
Hello,

I have been using this plugin without any problems for couple of days. I am not sure if next part has to do anything with the error or not, but I have installed WebStorm and ReasonML plugin for it, but I like this one better and decided to get back to VSCode. Then I got error:

```
ocamlmerlin error: Fatal error: exception Unix.Unix_error(Unix.ENOENT, "execve", "______________________________________________________________________________________/i/esy_ocaml__slash__merlin-3.0.5005-b827d4dc/bin/ocamlmerlin")

Source: OCaml and Reason IDE (Extension).

```

I have tried:
1. Reinstalling this plugin
2. Removing WebStorm plugin
3. Removing .merlin and creating it again

Nothing helped :(
How can I solve this issue so I can use this plugin again :) ?

**Comment by freebroccolo** [comment]
From that error it looks like something is wrong with the way that your development environment is configured. Something is failing from trying to load the `execve` binary which cannot be found. This isn't something the server normally does so I'm not sure where that's coming from.

Based on the path, it sounds like maybe you are trying to use esy. Unfortunately I don't have experience with that.

Can you try asking about this on the reason discord channel?

**Comment by mralj** [comment]
Thanks for the answer. 
I am not using Esy, so I am not sure why error is referencing it. I will ask on Discord :)

**Comment by mralj** [comment]
It seems there was some issue with my reason-cli. Running 

`yarn global add reason-cli@latest-macos`

Fixed issue :)
