### ISSUE TITLE
Autocomplete is a bit too aggressive

### ISSUE THREAD

**Issue by glennsl** [reasonml-editor/vscode-reasonml#44]
One particularly annoying  example is when typing semicolon followed (slowly) by enter, it will insert some random identifier. This is of course done on the end of most lines of code, so it happens quite often.

**Comment by Chillee** [comment]
@glennsl If you never use enter for autocomplete and use tab instead, you can do 
```
    "editor.acceptSuggestionOnEnter": "off",
```

**Comment by glennsl** [comment]
Oh cool, thanks! I'll try that out!

**Comment by Khady** [comment]
You can also use shift+enter to return to the next line without accepting the completion.

**Comment by glennsl** [comment]
@Khady That's a workaround, not a solution. As far as I'm aware this still doesn't work as intended and should be addressed.
