### ISSUE TITLE
Syntax Highlighting Dying in certain instances

### ISSUE THREAD

**Issue by kennetpostigo** [reasonml-editor/vscode-reasonml#47]
Here the syntax highlighting seems to die out on let bindings:
![image](https://cloud.githubusercontent.com/assets/8888991/24314878/4afbea84-10ba-11e7-944e-631a8b534722.png)

Here syntax highlighting dies on nested switch statements:
![image](https://cloud.githubusercontent.com/assets/8888991/24314934/965d1f02-10ba-11e7-8aaa-23f93142fce1.png)

**Comment by kennetpostigo** [comment]
I realized the culprit is rapping the function body in `{...}`

**Comment by freebroccolo** [comment]
I suspect the issue may be related to the `::` for punning which initially causes it to fail. What happens if you try something like `paths::paths`?

**Comment by kennetpostigo** [comment]
@freebroccolo you are right, once I do that the highlighting returns. However refmt will automatically return it to the punned labelled arguments version.

**Comment by freebroccolo** [comment]
Yeah, the syntax highlighting hasn't been updated for punned arguments yet. I was working on a rewrite of the syntax highlighting that is more accurate but I haven't had a chance to finish it yet. I'll try to spend some time on that next week.

**Comment by kennetpostigo** [comment]
@freebroccolo Awesome!

**Comment by freebroccolo** [comment]
@kennetpostigo Can you check if this is fixed for you now with the latest commit and whether you notice any new breakage? Just clone the repo, open repo director in `code`, and hit F5 to launch a development version of the extension, then try it on a file that was messed up before.

**Comment by freebroccolo** [comment]
Looks like the fix I introduced needs a little more work actually.

**Comment by freebroccolo** [comment]
I submitted another fix which I think finally resolves this. Let me know if it doesn't and I'll re-open.
