### ISSUE TITLE
Hitting after semicolon inserts pattern matching bar.

### ISSUE THREAD

**Issue by jordwalke** [reasonml-editor/vscode-reasonml#54]
Hi @freebroccolo. vscode-reasonml continues to be an excellent plugin.

I noticed one issue. When hitting enter after this semicolon, a pattern matching bar is inserted.

<img width="249" alt="screen shot 2017-05-07 at 10 38 41 pm" src="https://cloud.githubusercontent.com/assets/977348/25791558/1cfa6096-3376-11e7-88ba-170c25360075.png">

**Comment by freebroccolo** [comment]
Thanks for the feedback. I think this is related to some of the discussion in #46. Should be fixed in the upcoming release.

**Comment by Khady** [comment]
Release 1.0.0 doesn't fix the problem.
