### ISSUE TITLE
No definition found ...

### ISSUE THREAD

**Issue by kristojorg** [reasonml-editor/vscode-reasonml#58]
I'm not entirely sure this is an issue with vscode-reason, but I'm also not sure where else to look. I am starting a project with the `reason-react-example` code found [here](https://github.com/chenglou/reason-react-example). One of the files looks like this: 

```
module PageReason = {
  include ReactRe.Component.JsProps;
  type props = {message: string, extraGreeting: option string};
  let name = "PageReason";
  let render {props} => {
    let greeting =
      switch props.extraGreeting {
      | None => "How are you?"
      | Some g => g
      };
    <div> <MyBannerRe show=true message=(props.message ^ " " ^ greeting) /> </div>
  };
  /* extraGreeting is optional, which means the JS side might pass in a null or undefined */
  type jsProps = Js.t {. message : string, extraGreeting : Js.null_undefined string};
  let jsPropsToReasonProps =
    Some (
      fun jsProps => {
        message: jsProps##message,
        extraGreeting: Js.Null_undefined.to_opt jsProps##extraGreeting
      }
    );
};

include ReactRe.CreateComponent PageReason;

let createElement ::message ::extraGreeting=? => wrapProps {message, extraGreeting};
```

I am trying to understand where the `Js` variable is coming from, what it does etc. but jump to definition is not working on it, instead it says no definition found. This is also true of the `MyBannerRe` component, which is in a sibling file. 

Any help would be appreciated. Thank you!!

**Comment by kristojorg** [comment]
Update: It looks like go to definition is not working even within the same file

**Comment by freebroccolo** [comment]
The vscode plugin relies on feedback from merlin so it's possible that if the `.merlin` file for the project isn't configured properly that certain features like jump-to-definition won't work.

I'm guessing that for that project the `.merlin` file must be generated as part of the install process because I don't see it anywhere in the repo. I'll have to give it a try and see if I can figure out what is going wrong.

It looks like that [`Js` module](https://bloomberg.github.io/bucklescript/Manual.html#_js_module) is from Bucklescript though.

**Comment by cristianoc** [comment]
@freebroccolo something I've noticed is that vscode run from the command-line (at least on mac) picks up the .merlin from the directory where the file is opened.

For example, if .merlin is in the parent directory, then this does not pick it up
```
open test.re -a /Applications/Visual\ Studio\ Code.app/
```
Instead, Atom picks it up:
```
open test.re -a /Applications/Atom.app/
```

In addition, a couple of typical gotchas:
1) the .merlin file must be there, and should contain the correct paths
2) the reason and merlin executables should be in the path
3) the reason compilation artifacts should be there: remember to build
4) the reason and merlin executables should be for the right version (so if you switch between different ocaml/reason versions, remember to rebuild the compilation artifacts)

**Comment by cristianoc** [comment]
@kristojorg in the case of reason-react-example and `src/interop/pageReason.re`, if on Mac, I would do:
1) cd reason-react-example
2) npm run clean
3) npm run start
4) check editor setup here https://facebook.github.io/reason/jsWorkflow.html#javascript-workflow-editor-setup-global-utilities
5) open . -a /Applications/Visual\ Studio\ Code.app/, then navigate to `src/interop/pageReason.re`

**Comment by freebroccolo** [comment]
> For example, if .merlin is in the parent directory, then this does not pick it up
> 
> open test.re -a /Applications/Visual\ Studio\ Code.app/

Just to be clear, are we talking about a directory structure like this?

```
src
|- .merlin
|- test.re
```

... or like this?

```
project
|- .merlin
|- src
   |- test.re
```

Both cases can probably be dealt with but the second one will be messier due to the fact that vscode really wants to be opened in the project root.

**Comment by kristojorg** [comment]
The project does look like the second example. Thank you for the suggestion @cristianoc but unfortunately I am still not seeing definitions for any symbols being found (even if they are in the same file)

**Comment by freebroccolo** [comment]
Just for the record, I think this is related to #56 and it seems to be due to some problem in the interaction between this extension, merlin, and Bucklescript specifically.
