### ISSUE TITLE
Add a setting to exclude some files

### ISSUE THREAD

**Issue by Khady** [reasonml-editor/vscode-reasonml#80]
I have some files that are using extensions not supported by merlin (camlp4). Would be nice to have a way to exclude them. Or at least to have a command to avoid running merlin on them.

**Comment by freebroccolo** [comment]
Sounds reasonable. I've thought about having something like this before but put it off since I hadn't come up with a good interface for specifying files to exclude. Do any of the other OCaml editor modes support something like this?

**Comment by freebroccolo** [comment]
Dupe of #94 I think.
