### ISSUE TITLE
Incorrect name on marketplace

### ISSUE THREAD

**Issue by ShalokShalom** [reasonml-editor/vscode-reasonml#87]
This page here lists the plugin as reasonml, while its not found on this name. 
Reason works. 

https://marketplace.visualstudio.com/items?itemName=freebroccolo.reasonml

**Comment by freebroccolo** [comment]
I don't think this is really a problem to be honest. The plugin identifier name and plugin display name don't need to be the same necessarily. I will consider adding an additional keyword to help with searches but it's not worth renaming things right now.
