### ISSUE TITLE
Type inference not working

### ISSUE THREAD

**Issue by mrkaspa** [reasonml-editor/vscode-reasonml#89]
It looks like the type inference is not working properly, the first photo is from reasonml and the second is ocaml the type inference in ocaml is more exact

![foto 19-08-17 11 37 34 a m](https://user-images.githubusercontent.com/764271/29488545-fc9cec70-84d2-11e7-92da-64816d617e76.jpg)

![foto 19-08-17 11 37 45 a m](https://user-images.githubusercontent.com/764271/29488548-0673241c-84d3-11e7-918a-4ecc7a9ce9a9.jpg)

**Comment by Khady** [comment]
Can you share the code so that I can compare with the behavior in other editors. The problem might be from merlin.

**Comment by mrkaspa** [comment]
@Khady sure this is https://github.com/rdavison/llama-snake

**Comment by Khady** [comment]
I don't manage to reproduce with emacs:

![image](https://user-images.githubusercontent.com/974142/29492661-d49c9fde-85b5-11e7-90a2-9af04bf72715.png)

I installed a new 4.04.2 switch, installed merlin, reason.1.13.7, notty, jbuilder, called `make` and then opened `model.re`. It gives me the output from the screenshot.

I don't have a vscode available until tomorrow to try with your setup.

**Comment by mrkaspa** [comment]
may be it's a vscode issue

**Comment by Khady** [comment]
Sorry I didn't tested before today. You are using vscode-ocaml for your ocaml screenshot?

I can confirm the problem with vscode-reasonml, for both the ocaml and the reason versions of the code.

**Comment by mrkaspa** [comment]
@Khady yes I used vscode-ocaml

**Comment by freebroccolo** [comment]
I'm not sure what could be causing this but will investigate. It may be that the emacs mode is using different merlin commands or something like that.

**Comment by mrkaspa** [comment]
I think it is because of this https://github.com/chenglou/reason-project-ideas#show-the-reified-type-info-instead-of-the-generic-one

**Comment by chenglou** [comment]
Nono, that one isn't related

**Comment by freebroccolo** [comment]
@mrkaspa @Khady This seems to be working as expected as of version `1.0.11`. Can one of you verify?

OCaml:
![fixed-ocaml-opt](https://user-images.githubusercontent.com/151197/32705952-a27cf7a2-c7d6-11e7-8736-e0283564dbdc.png)

Reason:
![fixed-reason-opt](https://user-images.githubusercontent.com/151197/32705954-a7f5b23c-c7d6-11e7-8aa6-4f8fbff585a7.png)
