### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by chenglou** [reasonml-editor/vscode-reasonml#91]
Hey @freebroccolo, could you publish a new version of the plugin please? Mostly for the README update. The current Reason.section on the marketplace still points to the stale Reason setup page.

**Comment by freebroccolo** [comment]
Okay. I'll probably shoot for this weekend since I need to test a couple of things first before release.

**Comment by freebroccolo** [comment]
So I've been working on this over the last few days but it's going to take me a little longer to get to a new release state. There's still some broken stuff in the master branch here and in the server repo that needs to be sorted out first otherwise it will just create more of a mess.

**Comment by fhelwanger** [comment]
Sorry to add more work, but if you could update the `ocaml-language-server` dependency I'd be very grateful 😄 

https://github.com/freebroccolo/ocaml-language-server/pull/29 is the only thing preventing this extension from working on Windows using https://github.com/fhelwanger/ocaml-on-windows

**Comment by freebroccolo** [comment]
Yeah, I plan to release a new version of both simultaneously and update the dependencies.

**Comment by fhelwanger** [comment]
@freebroccolo Nice, thanks! 🎉

**Comment by freebroccolo** [comment]
New releases of the plugin and the server have been released.
