### ISSUE TITLE
Merlin configuration

### ISSUE THREAD

**Issue by ShalokShalom** [reasonml-editor/vscode-reasonml#95]
The OCaml plugin supports Merlin configuration out of the box: Can we add that too?

https://github.com/hackwaly/vscode-ocaml#features

**Comment by freebroccolo** [comment]
This plugin does use merlin automatically for most features if that is what you are asking. Actually it's a little bit more complicated than that because the plugin uses ocaml-language-server, but most of the language server features are built around merlin.

**Comment by ShalokShalom** [comment]
Does it make sense to suggest the installation of this plugin in order to setup the paths in an easy way?

**Comment by freebroccolo** [comment]
Which plugin? The `vscode-ocaml` one? Probably not if that's what you mean. The binary paths normally don't need to be set manually except under special circumstances where you might have multiple versions installed and want to use a specific one. The ocaml server will use whichever paths resolve from the environment. So the user doesn't really have to do anything special to get merlin to work as long as it is installed and in their `PATH`.

**Comment by ShalokShalom** [comment]
I mixed that with: 

This extension relies heavily on merlin so you will need to have your project set up for that in order to enable completion and hover info. See the Merlin wiki for details on how to do that. Basically you need to have a .merlin file in your project root which lists the source directories, libraries, and extensions used.

**Comment by freebroccolo** [comment]
That paragraph is just talking about configuring your project for use with merlin. It's not specific to this plugin; the other ocaml plugin behaves the same way. You can see more about what is required to configure merlin [here](https://github.com/ocaml/merlin/wiki/Project-configuration).

**Comment by freebroccolo** [comment]
I'm going to close this since I think the original question was addressed. Feel free to comment though if you still have a question about this.

**Comment by ShalokShalom** [comment]
Forgive me, but this happens in Reason while OCaml works out of the box:
![screenshot_20170830_234356](https://user-images.githubusercontent.com/6344099/29896422-3064ccd6-8ddd-11e7-897a-d4666ad02450.png)

**Comment by freebroccolo** [comment]
Can you give me a little more information about your setup?

Which version of the plugin are you using? Do you have merlin installed through opam? What happens if you try to run `ocamlmerlin` from the bash shell? Can you provide the output of running `which ocamlmerlin`?

**Comment by ShalokShalom** [comment]
It seems like OCaml simply does not give any error message, when Merlin isnt installed.

Solved.
